name: "Deploy Terraform to AWS with S3 State Backend"

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:  # Allow manual execution
    inputs:
      action:
        description: "Choose action (plan, apply, or destroy)"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    name: "Terraform Deployment"
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "us-east-1"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: "Set Environment Variables Based on Branch"
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "TERRAFORM_DIR=prod" >> $GITHUB_ENV
            echo "TERRAFORM_BUCKET=prod-bethel-air-tfstate" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            echo "TERRAFORM_DIR=dev" >> $GITHUB_ENV
            echo "TERRAFORM_BUCKET=dev-bethel-air-tfstate" >> $GITHUB_ENV
          else
            echo "Unsupported branch: ${GITHUB_REF_NAME}"
            exit 1
          fi

      - name: "Initialize Terraform"
        run: |
          terraform init \
            -backend-config="key=${{ env.TERRAFORM_DIR }}-bethel-air.tfstate" \
            -backend-config="bucket=${{ env.TERRAFORM_BUCKET }}" \
            -backend-config="region=us-east-1"

      - name: "Terraform Plan"
        if: ${{ github.event.inputs.action == 'plan' }}
        run: terraform plan -out=plan.tfplan -var-file="${{ env.TERRAFORM_DIR }}/terraform.tfvars"

      # - name: "Terraform Apply"
      #   if: ${{ github.event.inputs.action == 'apply' }}
      #   run: terraform apply -auto-approve plan.tfplan
