name: "Deploy Terraform to AWS with S3 State Backend"

on:
  push:
    branches:
      - develop
      - main
  workflow_dispatch:
    inputs:
      action:
        description: "Choose action (plan, apply, or destroy)"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply

jobs:
  terraform:
    name: "Terraform Deployment"
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "us-east-1"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v4
        with:
          clean: false
          fetch-depth: 1
          persist-credentials: true
          sparse-checkout: false

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: "Determine Environment"
        id: env
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "env_dir=/home/runner/work/bethel-air-infra/bethel-air-infra/prod" >> $GITHUB_ENV
            echo "s3_bucket=prod-bethel-air-tfstate" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF_NAME}" == "develop" ]]; then
            echo "env_dir=/home/runner/work/bethel-air-infra/bethel-air-infra/dev" >> $GITHUB_ENV
            echo "s3_bucket=dev-bethel-air-tfstate" >> $GITHUB_ENV
          else
            echo "Unsupported branch: ${GITHUB_REF_NAME}"
            exit 1
          fi

      # - name: "Change Directory"
      #   run: |
      #     cd ${{ env.env_dir }}
      #     echo "Switched to directory: $PWD"

      - name: "Initialize Terraform"
        run: |
          terraform init \
            -backend-config="key=${{ env.env_dir }}\dev-bethel-air.tfstate" \
            -backend-config="bucket=${{ env.s3_bucket }}" \
            -backend-config="region=us-east-1"

      - name: "Terraform Plan"
        if: ${{ github.event.inputs.action == 'plan' }}
        run: terraform plan -out=plan.tfplan"

      - name: "Terraform Apply"
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -auto-approve plan.tfplan
