name: "Deploy Terraform to AWS with S3 State Backend"

on:
  push:
    branches:
      - develop
  workflow_dispatch:  # Allow manual execution
    inputs:
      action:
        description: "Choose action (plan, apply, or destroy)"
        required: true
        default: "plan"
        type: choice
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    name: "Terraform Deployment"
    runs-on: ubuntu-latest

    env:
      AWS_REGION: "us-east-1"

    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      - name: "Set up Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.2

      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 4: Initialize Terraform
      - name: "Terraform Init"
        run: terraform init

      # Step 5: Terraform Plan
      - name: "Run Terraform Plan"
        if: ${{ github.event.inputs.action == 'plan' }}
        run: terraform plan -out=plan.tfplan

      # # Step 6: Terraform Apply
      # - name: "Run Terraform Apply"
      #   if: ${{ github.event.inputs.action == 'apply' }}
      #   run: terraform apply -auto-approve plan.tfplan

      # # Step 7: Terraform Destroy
      # - name: "Run Terraform Destroy"
      #   if: ${{ github.event.inputs.action == 'destroy' }}
      #   run: terraform destroy -auto-approve
